### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sonicrules11** [sonicrules11/discord-bot#1]
- [ ] Seperate commands from main file 
- [ ] Actually update the README properly
- [ ] Voice connection
- [ ] Proper info commands
